[package]
name = "anchor-derive-serde"
version = "0.27.0"
authors = ["Serum Foundation <foundation@projectserum.com>"]
repository = "https://github.com/coral-xyz/anchor"
license = "Apache-2.0"
description = "Anchor Derive macro for serialization and deserialization"
rust-version = "1.56"
edition = "2021"

[lib]
proc-macro = true

[features]
idl-gen = [
    "anchor-syn/idl-gen",
]

[dependencies]
proc-macro2 = "1.0"
borsh-derive-internal = "0.9"
syn = { version = "1.0.60", features = ["full"] }
anchor-syn = { path = "../../syn", version = "0.27.0" }
quote = "1.0"
